### ISSUE TITLE
Problems with the raster.generate function ?

### ISSUE THREAD

**Issue by ambarja** [VIDA-NYU/tile2net#36] opened 2023-08-20 15:32 UTC
@Mary-h86 I recently generated my own tiles from a drone image with QGIS as you recommended in the issue #34
Here the output 👇 

![tilesss](https://github.com/VIDA-NYU/tile2net/assets/23284899/5d53015b-9426-4014-8e7d-6a059923b562)

![image](https://github.com/VIDA-NYU/tile2net/assets/23284899/be9fdb59-b188-4bc2-afd6-5910a2c9504d)
![image](https://github.com/VIDA-NYU/tile2net/assets/23284899/4f9560c8-a50e-4abb-9765-3d6ea9488b27)
![image](https://github.com/VIDA-NYU/tile2net/assets/23284899/ff9c4c9d-efc9-4ed6-b6ba-5492c8bc6047)

However, when I run my code especially in `raster.generate(2)` in Google Colab I have problems, first it does not generate the `structure.json` as in the reproducible example, so I wonder how can I implement my own image with tile2net in this part?

**Comment by Mary-h86** [comment] 2023-08-21 14:48
The location parameter you are passing is incorrect geographically and not in the right order! your latitude should be positive (+12.117778919,+12.116177610) and your coordinates should be passed in"lat ,lon, lat, lon" order. The location you entered is not valid, that is why the tool cannot build the correct grid to pair your tiles with it. 

We highly recommend reading the two preparation guides carefully and if you are unsure, always check your coordinates with google maps to make sure you are passing the correct values.

**Comment by ambarja** [comment] 2023-08-21 15:36
I have just put the coordinates according google maps, but I have the same problem. 
We have negative coordinates for Peru. How would I deal with that?
![image](https://github.com/VIDA-NYU/tile2net/assets/23284899/92a66597-a150-4653-84dc-0e4195008979)

**Comment by Mary-h86** [comment] 2023-08-21 15:51
The problems lies in the mismatch between your tile and the location you are passing. 
Based on the tile coordinates (tile numbers) from your screenshot, the lat and long are in the (12.117, -77.02) vicinity. 
`from tile2net.raster.tile_utils.genutils import num2deg`
`num2deg(299945,488726, 20)`
> (12.117879519823527, -77.02205657958984)

This means that your tiling was done incorrectly. 
Did you project your images to 4326 first before tiling? 
What is the extent shown on your QGIS extent when you want to pass it to create the tiles?

**Comment by ambarja** [comment] 2023-08-21 16:47
I have generated my tiles using QGIS and boundary box I have taken from the qgis tool itself, as shown in the screenshot.
I hereby attach the image used.
 - [drone image](https://drive.google.com/u/1/uc?id=1-mZGVfKNtOuSSC4PsY5pJlhErYf6JQXj&export=download)
![image](https://github.com/VIDA-NYU/tile2net/assets/23284899/c92bc1cf-8ec4-42f3-9835-4bd915e1ca63)

**Comment by Mary-h86** [comment] 2023-08-22 15:07
@ambarja 
Thank  you for providing the images. 
As we discussed yesterday, the problem is that your tile numbers (x,y) tiles do not match your location. 
The tile numbers shown in your screenshot correspond to a region in the opposite latitude (positive lat) compared to your region. The raster creates a grid based on the coordinates you passed, and it cannot locate the correct tiles to stitch since the numbers do not match.  

Looking at your code, your input_dir argument does not seem to be correct, unless you changed the name and folder structure. 

I created the tiles using QGIS: 
[QGIS_Tiles](https://www.dropbox.com/scl/fo/2nsgv9o2dbgtx8ag590gu/h?rlkey=cr5qsdzmrskynnlzw3fnlrch3&dl=0)
and did the stitch, which works (stitched are also there)

Lets say you have the tiles saved in a folder called test (use the ones attached):

```python
location = '-12.11760696,-77.02180781,-12.11635790,-77.02005634'
raster = Raster(
    location=location,
    name='lima_test',
    input_dir='./test/20/x/y.png',
    output_dir = './test',
    zoom = 20
)
``` 
Now you can easily check what tile coordinates your Raster object expects:

`raster.xtile` min xtile
> 299945

`raster.xtilem` max xtile
> 299950

`raster.ytile` max ytile
> 559849

`raster.ytilem `  min ytile
> 559845

So the ytiles (the name of your png files ) should be between 559845 and 559849, which based on your screenshot, they were not. 
One important point to note is the model is trained on the US cities where sidewalks generally have different materials compared to roads and the urban fabric is also different. The detection model unfortunately may not work as well in  your region, which is something we cannot address at the moment but it is in our extend our training data to be more generalizable. 

Good Luck!

**Comment by ambarja** [comment] 2023-08-22 15:24
@Mary-h86 First of all thank you very much for your support, I understand that the models were initially trained in the USA, therefore the results in other areas may not be as adequate.
Is there a way to improve the model? 
Thank you very much for everything.

**Comment by Mary-h86** [comment] 2023-08-22 22:51
@ambarja 
Happy to help and glad to see that you are making the effort to map the pedestrian infrastructure in your area! Great job! 
Regarding improving the model, this means additional training on new regions and for that, we need training data from your region: the orthorectified imagery together with the planimetric polygons of roads, sidewalks and crosswalks,  created based on the imagery so we can generate the training labels. Once we have that, I can go ahead and train the model on the new dataset. 

Regarding QGIS, to be honest, I only use it for tiling purposes, and the version I am using now is : _3.30.3-'s-Hertogenbosch - QGIS code revision c006973ad1_ on linux. I am not sure in what way your output is different, but i could see that the tiling was not done correctly for some reason. Our plan is to implement our own version of tiling later, as part of Tile2Net, so users are nor dependent on another tool to tile up their large images. 

Since this was not a problem with Tile2Net and hopefully it is resolved now, I close this issue!

**Closed by Mary-h86** 2023-08-22 22:51 UTC
