### ISSUE TITLE
A problem with stitched tiles and generate

### ISSUE THREAD

**Issue by Narjes97** [VIDA-NYU/tile2net#66] opened 2024-04-29 20:04 UTC
Hi,

I am trying to use this tool for Rhode Island to get its network. I am using the 2020 Spring Rhode Island Digital Orthophotographs for this purpose and am using "Generate XYZ Tiles (Directory)" for converting the tiff file to 256*256 png files. I have considered a small area in Rhode Island as a location first. After running the code, although the code gives me a directory of stitched tiles, it is empty, and I cannot understand why. I think this is the reason that I get an error while running "generate". Could you please help me with this issue?

![Screenshot from 2024-04-29 15-37-42](https://github.com/VIDA-NYU/tile2net/assets/123910941/842315ac-9859-42c7-b773-52b0e9924c21)

![Screenshot from 2024-04-29 15-42-30](https://github.com/VIDA-NYU/tile2net/assets/123910941/854c79c0-acaf-477d-ac20-87576ac9040c)

![Screenshot from 2024-04-29 15-45-14](https://github.com/VIDA-NYU/tile2net/assets/123910941/bc316242-1cdd-4998-b7d3-5ce9cb17ed01)

**Comment by Mary-h86** [comment] 2024-04-29 20:10
@Narjes97 
Thank you for using Tile2Net. 
From what I see of your path, seems like your zoom level should be 19 and you are passing 20, if that is the case, then the tool cannot find the x and y of tile associated with zoom level 20 and it is throwing the error. 
Change the zoom argument to be 19 instead and run again. 

Let me know if that solves the problem.

**Comment by Narjes97** [comment] 2024-04-30 00:26
I have changed the zoom level to 19, but the problem still exists. There is no folder named "256_19_1" when I run the raster.project.tiles.stitched command. I still get error while running generate.

![Screenshot from 2024-04-29 20-18-20](https://github.com/VIDA-NYU/tile2net/assets/123910941/8ee85261-5e88-4f16-8487-8ff9d9b1e413)


![Screenshot from 2024-04-29 20-21-17](https://github.com/VIDA-NYU/tile2net/assets/123910941/62543c9e-f303-4b25-9f20-458bba9c34fd)


![Screenshot from 2024-04-29 20-22-00](https://github.com/VIDA-NYU/tile2net/assets/123910941/88a9c37b-386f-4a08-aad8-7e80b1bd2a6d)

**Comment by Mary-h86** [comment] 2024-04-30 00:57
@Narjes97 
I am not quite sure what you want to do here, but, it seems to me that you are trying to run the example (the location lat long is from within Boston Common). I don't see Rhode Island coordinates passed to your Raster object. 

If you want to run the example, it means that you are running for an area that we support, which is in Massachusetts and you don't need to pass an `input_dir` for it since the tool automatically downloads and stitches the tiles for you. 
No `input_dir` argument is required. 

But if you are trying to see how passing `input_dir` works,  and you have your own tiles for the same area of Boston, can you run the `tree` command  for me (if you are using Linux)  from the `./static' folder? If not using linux, run this:
```bash
import os
os.listdir("./static")
```
and paste the results here?

**Comment by Narjes97** [comment] 2024-05-05 22:19
Hi, 
Sorry for the misunderstanding. I want to run the tile2net tool on Rhode Island to get its network. I had the tiff file of this area and I used "Generate XYZ Tiles (Directory)" tool in qgis for converting the tiff file to 256*256 png files and I did it foe zoom = 16. At first, I gave a small bounding box in Rhode Island as the location. Also, I gave the folder of 256*256 png files as my input. But it seems that the tool does not use my input at all. because when I make the input line as comment, the code still finds tiles. Here, I have attached the screenshots:

![Screenshot from 2024-05-05 18-06-15](https://github.com/VIDA-NYU/tile2net/assets/123910941/92174929-46b8-4bd8-a2db-a8ccf8077f32)


![Screenshot from 2024-05-05 18-06-56](https://github.com/VIDA-NYU/tile2net/assets/123910941/15ac5ac4-c716-4dc0-b533-12b6c00cc844)


Then, I just gave rhode_island as my location with no bounding box and the code finds tiles without using my input:


![Screenshot from 2024-05-05 18-09-00](https://github.com/VIDA-NYU/tile2net/assets/123910941/be1f604b-875b-499a-a9e2-41603b31feaa)

I am not sure what is really going on :) for all these cases, I still get the previous error in generate and also there are no stitched tiles in the directory. These are the screenshots of these steps:


![Screenshot from 2024-05-05 18-11-13](https://github.com/VIDA-NYU/tile2net/assets/123910941/209bf381-2465-497d-8f5c-71faf584e38a)

![Screenshot from 2024-05-05 18-11-57](https://github.com/VIDA-NYU/tile2net/assets/123910941/e34bb88f-7f5a-4c35-84b0-ff161bc8bb37)

![Screenshot from 2024-05-05 18-12-16](https://github.com/VIDA-NYU/tile2net/assets/123910941/3edd8a10-07b8-4fec-8048-d28ed07e6e87)

**Comment by Mary-h86** [comment] 2024-05-05 23:19
@Narjes97 
There are a few arguments that are not passed correctly in your code. But before getting into those details, since you used QGIS for tiling your region, by default, the path structure for your tiles should be like: `./Rhode_Island/16/x/y.png` , the `input_dir` you entered does not match that pattern. 
To confirm, as I requested before, could you please either run the `tree` command from inside your `./Rhode_Island` directory in Linux terminal or paste the absolute path to one of your tile files that you created using QGIS.

**Comment by Narjes97** [comment] 2024-05-07 03:18
The tree command does not work on my Linux terminal. It is an Alienware and for installing a tree, it needs some permission that I cannot access. But I used the other command you suggested:

![Screenshot from 2024-05-06 23-05-08](https://github.com/VIDA-NYU/tile2net/assets/123910941/22739128-3a41-4e5a-b8a4-3108248ddc98)

Also, I was able to run generate command:

![Screenshot from 2024-05-06 23-05-31](https://github.com/VIDA-NYU/tile2net/assets/123910941/bccdf2e4-b252-4cb4-95d5-5b3161b87f2b)

But now I get an error while running the inference command:


![Screenshot from 2024-05-06 23-06-11](https://github.com/VIDA-NYU/tile2net/assets/123910941/94b21fb4-c76e-4138-a862-d99f1ff170db)
![Screenshot from 2024-05-06 23-06-28](https://github.com/VIDA-NYU/tile2net/assets/123910941/b64c8f68-03bd-4d8e-a0b2-99f498d777b8)
![Screenshot from 2024-05-06 23-06-42](https://github.com/VIDA-NYU/tile2net/assets/123910941/9769a366-41fa-4d26-8d10-7174b3b056b8)

Could you please help me with this step as well?

**Comment by Narjes97** [comment] 2024-05-14 02:06
Hi,

I just wanted to make sure you have received my previous comment since I have not heard from you :)

**Comment by Mary-h86** [comment] 2024-05-14 17:24
@Narjes97 
Hi Narjes, yes we have received it but our team has been pretty busy with various deadlines the past few weeks. I will try to get back to you by the end of the week!

**Comment by Mary-h86** [comment] 2024-05-15 00:41
@Narjes97 
Your GPU is not being recognized and the process is running on CPU instead. 

can you run 
```bash 
Import torch 
print(torch.cuda.is_available())
print(torch.cuda.device_count()) 
print(torch.cuda.current_device())
```

Can you use a terminal window instead of the Jupyter notebook and run nvidia-smi? 

Send me the outputs of these so I can better assist you.

**Comment by Narjes97** [comment] 2024-05-19 22:11
![Screenshot from 2024-05-19 18-04-13](https://github.com/VIDA-NYU/tile2net/assets/123910941/bf788fa8-7c0a-4a5f-9c38-7599c9a61ec6)

![Screenshot from 2024-05-19 18-06-23](https://github.com/VIDA-NYU/tile2net/assets/123910941/6a1d0727-01de-4255-afaa-8bc8b9fdd68c)

**Comment by Mary-h86** [comment] 2024-05-19 22:45
Yes. So as I expected, the problem is related to your GPU and the output you got from `nvidia-smi` can typically mean there is a conflict between the NVIDIA driver and the NVML (NVIDIA Management Library) versions installed on your system. 
This is not a Tile2Net related issue and unfortunately, I cannot help that much with it. To be able to use your GPU, You need to resolve this issue, and make sure that you get a correct output from `nvidia-smi`, as well as the torch commands I sent before. The first one should return True and then you will get the number of available GPUs and the index of your currently selected GPU. 
When you run `nvidia-smi` outside the environment, do you get a correct output?

**Comment by Mary-h86** [comment] 2024-06-06 20:28
I am closing this issue. Feel free to re-open if you have any other questions.

**Closed by Mary-h86** 2024-06-06 20:28 UTC
